name: Scheduled Run and Release

on:
  schedule:
    - cron: "0 */2 * * *" # Every 2 hours
  workflow_dispatch: # Allows manual execution of the workflow.

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        run: python main.py
        continue-on-error: true

      - name: Stage changes in docs and check for changes
        id: changes
        run: |
          git add ./docs/
          if git diff --cached --quiet; then
            echo "no_changes=true" >> $GITHUB_ENV
          else
            echo "no_changes=false" >> $GITHUB_ENV
            git diff --cached --name-only > staged_files.txt
            # Export the changed files as a multiline environment variable
            echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
            cat staged_files.txt >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi

      - name: Commit and push changes to gh_pages branch
        if: success() && env.no_changes == 'false'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git checkout -b gh_pages
          git add ./docs/
          git commit -m "Update docs in gh_pages branch"
          git push origin gh_pages --force

      - name: Create Release
        if: success() && env.no_changes == 'false'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.run_number }}"
          name: "Stundenplan Release nr. ${{ github.run_number }}"
          body: "Neuer Stundenplan gefunden!"
          draft: false
          prerelease: false
          files: ${{ env.CHANGED_FILES }}
