name: Scheduled Run and Release

on:
  schedule:
    - cron: "0 */2 * * *" # Every 2 hours
  workflow_dispatch: # Allows manual execution of the workflow.

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        run: python main.py
        continue-on-error: true

      - name: Stage changes in docs and check for changes
        id: changes
        run: |
          git add ./docs/
          if git diff --cached --quiet; then
            echo "no_changes=true" >> $GITHUB_ENV
          else
            echo "no_changes=false" >> $GITHUB_ENV
            git diff --cached --name-only > staged_files.txt
          fi

      - name: Commit and push changes
        if: success() && env.no_changes == 'false'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "Add new or updated timetable files"
          git push origin ${{ github.ref }}

      - name: Prepare files for release
        id: prepare_files
        if: success() && env.no_changes == 'false'
        run: |
          files=$(cat staged_files.txt)
          echo "files_for_release=$files" >> $GITHUB_ENV

      - name: Create Release
        if: success() && env.no_changes == 'false'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.run_number }}"
          name: "New Timetable release nr. ${{ github.run_number }}"
          body: "Neuer Stundenplan gefunden!"
          draft: false
          prerelease: false
          files: ${{ env.files_for_release }}
