name: Scheduled Run and Release

on:
  schedule:
    - cron: "0 */2 * * *" # Alle 2 Stunden
  workflow_dispatch: # Allows manual execution of the workflow.

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        run: python main.py

      - name: Detect changed files
        id: changes
        run: |
          git diff --name-only HEAD^ HEAD > changed_files.txt
          grep '^docs/' changed_files.txt > new_docs_files.txt || true

      - name: Commit and push changes
        if: success()
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ./docs/
          git commit -m "Add new or updated timetable files"
          git push origin ${{ github.ref }}

      - name: Create Release
        if: success() && ${{ steps.changes.outputs.changed_files != '' }}
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.run_number }}"
          name: "New Timetable release nr. ${{ github.run_number }}"
          body: "Neuer Stundenplan gefunden!"
          draft: false
          prerelease: false
          files: $(cat new_docs_files.txt)
